# 06 Ensemble Models - Customer Churn Prediction

## Objective
    - The goal of this project is to predict whether a customer will leave the company (churn) using ensemble learning algorithms
## Models Used

- Random Forest
- AdaBoost
- Gradient Boosting
- XGBoost
## Dataset

Dataset: IBM Telco Customer Churn Dataset
Target Variable:

- Churn

## Workflow

1. Load and explore the dataset.
2. Perform exploratory data analysis (EDA).
3. Preprocess the data.
4. Train ensemble models.
5. Evaluate model performance.
6. Compare the results.

## Evaluation Metrics

- Accuracy
- Precision
- Recall
- F1-Score
- ROC-AUC Score

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Load Dataset

In [2]:
df = pd.read_csv("../datasets/IBM_Telco_Customer_churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

## Data Exploration

In [3]:
df.shape

(7043, 21)

In [4]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [6]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

## Data Preprocessing

In [7]:
df.drop("customerID", axis=1, inplace=True)

In [8]:
df["TotalCharges"].dtype

In [9]:
df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)

In [10]:
df.isnull().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [11]:
df["TotalCharges"] = df["TotalCharges"].fillna(
    df["TotalCharges"].median()
)
type(df)

pandas.DataFrame

In [12]:
df.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [13]:
df.head(5)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [14]:
from sklearn.preprocessing import LabelEncoder
lr = LabelEncoder()
df["Churn"] = lr.fit_transform(df["Churn"])

In [15]:
df = pd.get_dummies(
    df,
    drop_first=True,
    dtype=int
)

In [16]:
df.shape

(7043, 31)

In [17]:
df.columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='str')

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7043 non-null   int64
 1   tenure                                 7043 non-null   int64
 2   MonthlyCharges                         7043 non-null   float64
 3   TotalCharges                           7043 non-null   float64
 4   Churn                                  7043 non-null   int64
 5   gender_Male                            7043 non-null   int64
 6   Partner_Yes                            7043 non-null   int64
 7   Dependents_Yes                         7043 non-null   int64
 8   PhoneService_Yes                       7043 non-null   int64
 9   MultipleLines_No phone service         7043 non-null   int64
 10  MultipleLines_Yes                      7043 non-null   int64
 11  InternetService_Fiber optic            7043 non-null   int64
 12  InternetService_No                     7043 non-null   int64
 13  OnlineSecurity_No internet service     7043 non-null   int64
 14  OnlineSecurity_Yes                     7043 non-null   int64
 15  OnlineBackup_No internet service       7043 non-null   int64
 16  OnlineBackup_Yes                       7043 non-null   int64
 17  DeviceProtection_No internet service   7043 non-null   int64
 18  DeviceProtection_Yes                   7043 non-null   int64
 19  TechSupport_No internet service        7043 non-null   int64
 20  TechSupport_Yes                        7043 non-null   int64
 21  StreamingTV_No internet service        7043 non-null   int64
 22  StreamingTV_Yes                        7043 non-null   int64
 23  StreamingMovies_No internet service    7043 non-null   int64
 24  StreamingMovies_Yes                    7043 non-null   int64
 25  Contract_One year                      7043 non-null   int64
 26  Contract_Two year                      7043 non-null   int64
 27  PaperlessBilling_Yes                   7043 non-null   int64
 28  PaymentMethod_Credit card (automatic)  7043 non-null   int64
 29  PaymentMethod_Electronic check         7043 non-null   int64
 30  PaymentMethod_Mailed check             7043 non-null   int64
dtypes: float64(2), int64(29)
memory usage: 1.7 MB

In [19]:
bool_cols = df.select_dtypes(include="bool").columns
df[bool_cols] = df[bool_cols].astype(int)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7043 non-null   int64
 1   tenure                                 7043 non-null   int64
 2   MonthlyCharges                         7043 non-null   float64
 3   TotalCharges                           7043 non-null   float64
 4   Churn                                  7043 non-null   int64
 5   gender_Male                            7043 non-null   int64
 6   Partner_Yes                            7043 non-null   int64
 7   Dependents_Yes                         7043 non-null   int64
 8   PhoneService_Yes                       7043 non-null   int64
 9   MultipleLines_No phone service         7043 non-null   int64
 10  MultipleLines_Yes                      7043 non-null   int64
 11  InternetService_Fiber optic            7043 non-null   int64
 12  InternetService_No                     7043 non-null   int64
 13  OnlineSecurity_No internet service     7043 non-null   int64
 14  OnlineSecurity_Yes                     7043 non-null   int64
 15  OnlineBackup_No internet service       7043 non-null   int64
 16  OnlineBackup_Yes                       7043 non-null   int64
 17  DeviceProtection_No internet service   7043 non-null   int64
 18  DeviceProtection_Yes                   7043 non-null   int64
 19  TechSupport_No internet service        7043 non-null   int64
 20  TechSupport_Yes                        7043 non-null   int64
 21  StreamingTV_No internet service        7043 non-null   int64
 22  StreamingTV_Yes                        7043 non-null   int64
 23  StreamingMovies_No internet service    7043 non-null   int64
 24  StreamingMovies_Yes                    7043 non-null   int64
 25  Contract_One year                      7043 non-null   int64
 26  Contract_Two year                      7043 non-null   int64
 27  PaperlessBilling_Yes                   7043 non-null   int64
 28  PaymentMethod_Credit card (automatic)  7043 non-null   int64
 29  PaymentMethod_Electronic check         7043 non-null   int64
 30  PaymentMethod_Mailed check             7043 non-null   int64
dtypes: float64(2), int64(29)
memory usage: 1.7 MB

## Train Test Split

In [21]:
X = df.drop("Churn", axis=1)

y = df["Churn"]

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [23]:
from sklearn.ensemble import (
    RandomForestClassifier,
    AdaBoostClassifier,
    GradientBoostingClassifier
)
from xgboost import XGBClassifier

In [24]:
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)

In [25]:
import sys
import os

project_root = os.path.abspath("..")
sys.path.append(project_root)

print(project_root)

c:\Users\SAHADHEEP\OneDrive\Documents\Machine Learning\06

In [26]:
from src.ensemble_models import evaluate_model

In [27]:
print("Random Forest Classifier:")
evaluate_model(y_test, rf_pred)

Random Forest Classifier:

{'Accuracy': 0.7892122072391767,
 'Precision': 0.6428571428571429,
 'Recall': 0.4584450402144772,
 'F1-Score': 0.5352112676056338,
 'ROC-AUC': 0.6833730992578178}

In [28]:
ada = AdaBoostClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

ada.fit(X_train, y_train)
ada_pred = ada.predict(X_test)
print("AdaBoost Classifier:")
evaluate_model(y_test, ada_pred)

AdaBoost Classifier:

{'Accuracy': 0.7849538679914834,
 'Precision': 0.71875,
 'Recall': 0.30831099195710454,
 'F1-Score': 0.43151969981238275,
 'ROC-AUC': 0.6324373492604055}

In [29]:
gb = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

gb.fit(X_train, y_train)
gb_pred = gb.predict(X_test)
print("Gradient Boosting Classifier:")
evaluate_model(y_test, gb_pred)

Gradient Boosting Classifier:

{'Accuracy': 0.8090844570617459,
 'Precision': 0.6721854304635762,
 'Recall': 0.5442359249329759,
 'F1-Score': 0.6014814814814815,
 'ROC-AUC': 0.7243380396865653}

In [30]:
xgb = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

xgb.fit(X_train, y_train)
xgb_pred = xgb.predict(X_test)
print("XGBoost Classifier:")
evaluate_model(y_test, xgb_pred)

XGBoost Classifier:

{'Accuracy': 0.8112136266855926,
 'Precision': 0.6765676567656765,
 'Recall': 0.5495978552278821,
 'F1-Score': 0.606508875739645,
 'ROC-AUC': 0.7275016303166437}

In [31]:
rf_results = evaluate_model(y_test, rf_pred)

ada_results = evaluate_model(y_test, ada_pred)

gb_results = evaluate_model(y_test, gb_pred)

xgb_results = evaluate_model(y_test, xgb_pred)

In [32]:


comparison_df = pd.DataFrame(
    {
        "Random Forest": rf_results,
        "AdaBoost": ada_results,
        "Gradient Boosting": gb_results,
        "XGBoost": xgb_results
    }
).T

comparison_df

                   Accuracy  Precision    Recall  F1-Score   ROC-AUC
Random Forest      0.789212   0.642857  0.458445  0.535211  0.683373
AdaBoost           0.784954   0.718750  0.308311  0.431520  0.632437
Gradient Boosting  0.809084   0.672185  0.544236  0.601481  0.724338
XGBoost            0.811214   0.676568  0.549598  0.606509  0.727502